type Kind =
  | 'arrow-left'
  | 'arrow-right'
  | 'arrow-top-right'
  | 'bookmark'
  | 'bookmark-filled'
  | 'check'
  | 'check-circled'
  | 'chevron-down'
  | 'chevron-left'
  | 'chevron-right'
  | 'chevron-up'
  | 'circle'
  | 'code'
  | 'copy'
  | 'cross'
  | 'cross-circled'
  | 'double-arrow-left'
  | 'double-arrow-right'
  | 'hamburger'
  | 'hex-string'
  | 'input'
  | 'json'
  | 'loop'
  | 'magnifying-glass'
  | 'minus'
  | 'plus'
  | 'reload'
  | 'text';

// eslint-disable-next-line import/prefer-default-export
export type { Kind };
